#!/usr/bin/env bash
# Usage: rbenv version-file-read <file>
set -e
[ -n "$RBENV_DEBUG" ] && set -x

VERSION_FILE="$1"

if [ -e "$VERSION_FILE" ]; then
  # Read the first word from the specified version file. Avoid reading it whole.
  IFS="${IFS}"$'\r'
  words=( $(cut -b 1-1024 "$VERSION_FILE") )
  version="${words[0]}"

  if [ "$version" = ".." ] || [[ $version == */* ]]; then
    echo "rbenv: invalid version in \`$VERSION_FILE'" >&2
  elif [ -n "$version" ]; then
    variant_file=""

    if [[ "$(basename "$VERSION_FILE")" == ".ruby-version" ]]; then
      variant_file="$(dirname "$VERSION_FILE")/.ruby-variant"
    fi

    if [[ -e "$variant_file" ]]; then
      variant_words=( $(cat "$variant_file") )
      variant="${variant_words[0]}"

      if [ -n "$variant" ] && [[ "$version" != *-$variant ]]; then
        version="${version}-${variant}"
      fi
    fi

    echo "$version"
    exit
  fi
fi

exit 1
