name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'     

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rbenv_native_ext:
          - ""
          - "1"
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Bats testing framework
      run: |
        set -ex
        curl -fsSLo bats.tar.gz https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
        tar xzf bats.tar.gz
        mv bats-0.4.0 bats
    - name: Run tests
      run: |
        set -ex
        export PATH="./bats/bin:$PATH"
        export RBENV_NATIVE_EXT="${{ matrix.rbenv_native_ext }}"
        exec test/run
